adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
checkpointing_steps: 400
checkpoints_total_limit: null
comment: VAE finetune by Wasabi, test model using patched MSE
dataset_name: null
diffusers_xformers: true
gradient_accumulation_steps: 3
gradient_checkpointing: false
image_column: null
kl_scale: 1.0e-06
learning_rate: 1.0e-05
logging_dir: vae_log
lpips_scale: 0.5
lpips_start: 50001
lr_scheduler: constant
lr_warmup_steps: 0
max_data_loader_n_workers: 4
max_grad_norm: 1.0
mixed_precision: bf16
num_train_epochs: 1
output_dir: outputs/models_v4_bf16
patch_loss: false
patch_size: 64
patch_stride: 32
pretrained_model_name_or_path: /home/ckenny/models/FIBO/vae_bak/
report_to: tensorboard
resolution: 256
resume_from_checkpoint: null
revision: null
save_precision: bf16
scale_lr: false
seed: 420
test_data_dir: null
test_samples: 10
tracker_project_name: vae-fine-tune
train_batch_size: 4
train_data_dir: /home/ckenny/work/DV/datasets/cats/aligned/
train_only_decoder: true
use_8bit_adam: false
use_came: false
use_ema: false
validation_epochs: 1
